[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  skip_processing = false

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"